#!/usr/bin/env python3
# *_* coding: utf-8 *_*

"""Euler Project Problem 2."""

# -----------------------------------------------------------------------------

problem = {
    "title": "Even Fibonacci Numbers",
    "difficulty": 5,
    "description": r"""
        <p>Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with $1$ and $2$, the first $10$ terms will be:
        $$1, 2, 3, 5, 8, 13, 21, 34, 55, 89, \dots$$</p>
        <p>By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.</p>
    """,
    "answer": 4613732,
}

def generate_fibonacci():
    """Generator of Fibonacci numbers."""
    a, b = 1, 0
    while True:
        a, b = b, a + b
        yield a

def main():
    """Main function."""
    answer = 0
    for fib in generate_fibonacci():
        if fib >= 4000000:
            break
        if fib % 2 == 0:
            answer += fib
    return answer


if __name__ == "__main__":
    print(__doc__)
    print('"' + problem["title"] + '"')
    print("Expected answer:", problem["answer"])
    print("Computed answer:", main())
